name: ampd
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  path_provider: ^1.6.22
  intl: ^0.16.1
  font_awesome_flutter: ^8.8.1
  flutter_rating_bar: ^3.0.1+1
  extended_nested_scroll_view: ^1.0.1
  readmore: ^1.0.0
  flutter_staggered_grid_view: ^0.3.2
  path:
  keyboard_actions: ^3.3.0
  cached_network_image: ^2.5.0
  flutter_launcher_icons: ^0.8.1
  #  multi_image_picker: ^4.7.14
  dio: ^3.0.10
  toast: ^0.1.5
  data_connection_checker: ^0.3.4
  shared_preferences: ^0.5.12+2
  extended_image: 1.1.2
  flare_splash_screen: 3.0.1
  modal_progress_hud: ^0.1.3
  lottie:
  flutter_datetime_picker: ^1.4.0
  #bottom navigation bar
  animated_bottom_navigation_bar: ^0.2.0
  flutter_svg: ^0.19.0
  drawerbehavior: ^1.1.4
  bubble: ^1.1.9+1
  sizer: ^1.1.7
  #  image_picker: ^0.6.2
  carousel_slider: ^2.3.1
#  credit_card: ^0.1.8
#  credit_card_validator: ^1.1.0
  rect_getter: 0.0.1 #<-- add this
  datetime_picker_formfield: ^1.0.0
  #  media_picker_builder: ^1.3.2
  #  better_player: ^0.0.43
  #  better_player: ^0.0.53
#  story_view: ^0.12.8
  #  image_cropper: ^1.3.1
#  liquid_swipe: ^1.5.0
  circular_check_box: ^1.0.4
  #  photo_manager: ^0.5.8
#  video_player: ^1.0.1
  #  gallery_saver: ^2.0.3
  geocoder: ^0.2.1
#  connectivity: ^2.0.2
#  pin_code_fields: ^6.1.0
#  flutter_exif_rotation: ^0.3.2
  permission_handler: 3.1.0
  location_permissions: ^3.0.0
#  flutter_facebook_login: 3.0.0
#  google_sign_in: 4.5.4
  provider: 4.3.2+2
  geolocator:
  heic_to_jpg: ^0.1.3
  flutter_native_image: ^0.0.5+3
  flutter_pin_code_fields: ^1.1.0
#  flip_card: #^0.5.0
  flutter_xlider: ^3.4.0
  flutter_html:
  #  file_picker: ^2.0.6
#  stripe_payment: ^1.0.11
#  video_thumbnail: ^0.2.5+1
  infinite_scroll_pagination: ^2.3.0
  timeago: ^2.0.30
  flutter_switch:
  #  hashtagable: ^1.0.8
#  swipe_cards: ^0.0.5
  flip_card: ^0.4.4
  url_launcher: ^5.7.10
  map_launcher: ^1.1.3+1

  #FIREBASE
#  firebase_auth: ^0.18.1+1
#  firebase_messaging:
#  firebase_core:
#  firebase_database:
#  firebase_crashlytics:
#  firebase_core_platform_interface: ^2.1.0
#  flutter_absolute_path: ^1.0.6
#  webview_flutter: ^1.0.7
#  mime:
#  video_compress: ^2.1.0
#  flutter_masked_text: ^0.7.0
  #  draggable_widget: ^1.1.1
#  chewie: ^0.12.2
  #  get: ^3.25.6
#  images_picker:
  collection: #^1.15.0
  open_appstore: #^1.0.2

  #NOTIFICATION
  notification_permissions: 0.4.8
  flutter_local_notifications: ^1.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_icons:
  image_path_android: "assets/images/app_logo.png"
  image_path_ios: "assets/images/app_logo.jpg"
  android: "ic_launcher" # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: CeraPro
      fonts:
        - asset: assets/fonts/CeraPro-Medium.ttf
        - weight: 400

    - family: Nexa
      fonts:
        - asset: assets/fonts/Nexa-Light.otf
        - weight: 100
        - asset: assets/fonts/Nexa-Bold.otf
        - weight: 800


    - family: SFProText-Regular
      fonts:
        - asset: assets/fonts/SFProText-Regular.ttf
        - weight: 200

    - family: SFProText-Bold
      fonts:
        - asset: assets/fonts/SFProText-Bold.ttf
        - weight: 700

    - family: SFUIDisplay
      fonts:
        - asset: assets/fonts/SF-UI-Display-Regular.otf
        - weight: 200
        - asset: assets/fonts/SF-UI-Display-Semibold.ttf
        - weight: 400

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 100
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 400
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800